builds:
  - main: main.go
    binary: gost
    ldflags: -s -w -X github.com/gost-c/gost-cli/command.GitCommit={{.Commit}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^refactor'
      - '^tweak'
      - '^test'
