builds:
  - main: main.go
    binary: gost
    ldflags: -s -w -X github.com/gost-c/gost-cli/command.GitCommit={{.Commit}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
  files:
    - LICENSE
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^refactor'
      - '^tweak'
      - '^test'
