language: go
go:
- 1.8
install:
- go get -t -v ./...
- go get -v github.com/mitchellh/gox
script:
- chmod +x ./build.sh
- make build
deploy:
  provider: releases
  api_key:
    secure: lzeqjb4OWQTG349KHUWoya8DlaW7yDjwiEtyyq0e0dfPeDj1s8hF6Ra0U6LGCpDyAPQjFgGNxv9+a9pKJO/FxNDgXcxRbjxLTR6Qhv+w/Ud5OdhG+g3s2ntCg3bDWecaSiP4U9oY4oFy860CWdmOcXW97SjWmEiqryV/RDKvtnezqH4GVWaypeG19QXNyAFqiq5ttNIFQtRy+6JiSUBkzLIIK7SwWzX6Kh2C4vaPxXmjVxUAviAcCDdj106Tv6T8OfJRbfZiA6o3EuDaw5uhsUu4HEYpxwL21Tebg7Q75Gh90iJfkVzJudqXUAnRPmyj7jEYKnJ+thZP28/th9EMc6QUbhZMV9lECte1nGRA0+KtGNU9wjmuQYjrtTYWCWWq2s8SX2a3VnHrqi2J5z3nt8RX+GpvKeNRf1fy/FXwCHZjghZSSEM920ZwVGbFhKRasQ0+DUny6OBI1jsJyzHyWnHag0Gz1/OmsKy4Q34DxeYKVSzi4n3DBeNM4+TqBPqIHCZphzrA7vqlJWmM/30CobVTQWmHkuaJ/mmgGkgsqwI8GZRyxXc3jkqeVx4aYbgDH5kcOLuAOs7Pwq+lce6b/+9sGOJ0+KRIGlWF6Ql8j7xnumn4SsB8L53lcVDl9nyADy4ZfWCdMp0uMgZOM8dpAs4c/40Jt/9KcDbCWZBH3rg=
  file: bin/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: gost-c/gost-cli
